[package]
name = "roman-numerals"
version = "0.1.0"
authors = ["Michael Evans <michael.evans@ride.capital>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
